files:
  - web-greeter/resources/js/docs/LightDMObjects.js
  - web-greeter/resources/js/docs/Greeter.js
  - web-greeter/resources/js/docs/GreeterConfig.js
  - web-greeter/resources/js/ThemeUtils.js
  - web-greeter/resources/js/bootstrap.js
articles:
  - Overview: README.md
branches:
  - master
  - stable
