title: lightdm-webkit2-greeter
description: A LightDM greeter that uses Webkit2 for theming via HTML/JavaScript
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-mentions
  - jekyll-coffeescript
  - jekyll-paginate
